// Code generated by diameter-codegen. DO NOT EDIT.

package cx

// Protocol Constants
const (
	CX_APPLICATION_ID                          = 16777216
	DIAMETER_ERROR_AUTH_SCHEME_NOT_SUPPORTED   = 5006
	DIAMETER_ERROR_IDENTITIES_DONT_MATCH       = 5002
	DIAMETER_ERROR_IDENTITY_ALREADY_REGISTERED = 5005
	DIAMETER_ERROR_IDENTITY_NOT_REGISTERED     = 5003
	DIAMETER_ERROR_IN_ASSIGNMENT_TYPE          = 5007
	DIAMETER_ERROR_NOT_SUPPORTED_USER_DATA     = 5009
	DIAMETER_ERROR_ROAMING_NOT_ALLOWED         = 5004
	DIAMETER_ERROR_TOO_MUCH_DATA               = 5008
	DIAMETER_ERROR_USER_UNKNOWN                = 5001
	DIAMETER_SUBSEQUENT_REQUEST                = 4121
	LIR_COMMAND_CODE                           = 302
	MAR_COMMAND_CODE                           = 303
	PPR_COMMAND_CODE                           = 305
	RTR_COMMAND_CODE                           = 304
	SAR_COMMAND_CODE                           = 301
	UAR_COMMAND_CODE                           = 300
	VENDOR_ID_3GPP                             = 10415
)

// AVP Codes
const (
	AVPCode3GPPCHARGINGCHARACTERISTICS                uint32 = 13
	AVPCode3GPP2MEID                                  uint32 = 1471
	AVPCodeAMSISDN                                    uint32 = 1643
	AVPCodeAESECOMMUNICATIONPATTERN                   uint32 = 3113
	AVPCodeAIRFLAGS                                   uint32 = 1679
	AVPCodeAMBR                                       uint32 = 1435
	AVPCodeAPNCONFIGURATION                           uint32 = 1430
	AVPCodeAPNCONFIGURATIONPROFILE                    uint32 = 1429
	AVPCodeAPNOIREPLACEMENT                           uint32 = 1427
	AVPCodeAUTN                                       uint32 = 1449
	AVPCodeACCESSRESTRICTIONDATA                      uint32 = 1426
	AVPCodeACCOUNTINGREALTIMEREQUIRED                 uint32 = 483
	AVPCodeACCOUNTINGRECORDNUMBER                     uint32 = 485
	AVPCodeACCOUNTINGRECORDTYPE                       uint32 = 480
	AVPCodeACCOUNTINGSUBSESSIONID                     uint32 = 287
	AVPCodeACCTAPPLICATIONID                          uint32 = 259
	AVPCodeACCTINTERIMINTERVAL                        uint32 = 85
	AVPCodeACCTMULTISESSIONID                         uint32 = 50
	AVPCodeACCTSESSIONID                              uint32 = 44
	AVPCodeACTIVEAPN                                  uint32 = 1612
	AVPCodeACTIVETIME                                 uint32 = 1692
	AVPCodeADJACENTACCESSRESTRICTIONDATA              uint32 = 1673
	AVPCodeADJACENTPLMNS                              uint32 = 1672
	AVPCodeAERIALUESECURITYINFORMATION                uint32 = 1702
	AVPCodeAERIALUESUBSCRIPTIONINFORMATION            uint32 = 1699
	AVPCodeALERTREASON                                uint32 = 1434
	AVPCodeALLAPNCONFIGURATIONSINCLUDEDINDICATOR      uint32 = 1428
	AVPCodeALLOCATIONRETENTIONPRIORITY                uint32 = 1034
	AVPCodeAREASCOPE                                  uint32 = 1624
	AVPCodeASSOCIATEDIDENTITIES                       uint32 = 632
	AVPCodeASSOCIATEDREGISTEREDIDENTITIES             uint32 = 647
	AVPCodeAUTHAPPLICATIONID                          uint32 = 258
	AVPCodeAUTHGRACEPERIOD                            uint32 = 276
	AVPCodeAUTHREQUESTTYPE                            uint32 = 274
	AVPCodeAUTHSESSIONSTATE                           uint32 = 277
	AVPCodeAUTHENTICATIONINFO                         uint32 = 1413
	AVPCodeAUTHORIZATIONLIFETIME                      uint32 = 291
	AVPCodeBROADCASTLOCATIONASSISTANCEDATATYPES       uint32 = 1700
	AVPCodeCLRFLAGS                                   uint32 = 1638
	AVPCodeCSGID                                      uint32 = 1437
	AVPCodeCSGSUBSCRIPTIONDATA                        uint32 = 1436
	AVPCodeCALLBARRINGINFO                            uint32 = 1488
	AVPCodeCALLIDSIPHEADER                            uint32 = 643
	AVPCodeCANCELLATIONTYPE                           uint32 = 1420
	AVPCodeCHARGEDPARTY                               uint32 = 857
	AVPCodeCHARGINGINFORMATION                        uint32 = 618
	AVPCodeCLASS                                      uint32 = 25
	AVPCodeCLIENTIDENTITY                             uint32 = 1480
	AVPCodeCOLLECTIONPERIODRRMLTE                     uint32 = 1657
	AVPCodeCOLLECTIONPERIODRRMUMTS                    uint32 = 1658
	AVPCodeCOMMUNICATIONDURATIONTIME                  uint32 = 3119
	AVPCodeCOMMUNICATIONFAILUREINFORMATION            uint32 = 4300
	AVPCodeCOMMUNICATIONPATTERNSET                    uint32 = 3114
	AVPCodeCOMPLETEDATALISTINCLUDEDINDICATOR          uint32 = 1510
	AVPCodeCONFIDENTIALITYKEY                         uint32 = 1451
	AVPCodeCONTACT                                    uint32 = 641
	AVPCodeCONTEXTIDENTIFIER                          uint32 = 1423
	AVPCodeCORENETWORKRESTRICTIONTYPE                 uint32 = 1705
	AVPCodeCORENETWORKRESTRICTIONS                    uint32 = 1704
	AVPCodeCOUPLEDNODEDIAMETERID                      uint32 = 1666
	AVPCodeCURRENTLOCATION                            uint32 = 707
	AVPCodeDLBUFFERINGSUGGESTEDPACKETCOUNT            uint32 = 1674
	AVPCodeDRMP                                       uint32 = 301
	AVPCodeDSAFLAGS                                   uint32 = 1422
	AVPCodeDSAITAG                                    uint32 = 711
	AVPCodeDSRFLAGS                                   uint32 = 1421
	AVPCodeDATAREFERENCE                              uint32 = 703
	AVPCodeDAYLIGHTSAVINGTIME                         uint32 = 2350
	AVPCodeDEREGISTRATIONREASON                       uint32 = 615
	AVPCodeDESTINATIONHOST                            uint32 = 293
	AVPCodeDESTINATIONREALM                           uint32 = 283
	AVPCodeDIGESTALGORITHM                            uint32 = 111
	AVPCodeDIGESTHA1                                  uint32 = 121
	AVPCodeDIGESTQOP                                  uint32 = 110
	AVPCodeDIGESTREALM                                uint32 = 104
	AVPCodeDISCONNECTCAUSE                            uint32 = 273
	AVPCodeEUTRANVECTOR                               uint32 = 1414
	AVPCodeE2ESEQUENCE                                uint32 = 300
	AVPCodeEPSLOCATIONINFORMATION                     uint32 = 1496
	AVPCodeEPSSUBSCRIBEDQOSPROFILE                    uint32 = 1431
	AVPCodeEPSUSERSTATE                               uint32 = 1497
	AVPCodeEMERGENCYINFO                              uint32 = 1687
	AVPCodeEMERGENCYREGISTRATIONRESULT                uint32 = 652
	AVPCodeEMERGENCYSERVICES                          uint32 = 1538
	AVPCodeEQUIPMENTSTATUS                            uint32 = 1445
	AVPCodeEQUIVALENTPLMNLIST                         uint32 = 1336
	AVPCodeERRORDIAGNOSTIC                            uint32 = 1614
	AVPCodeERRORMESSAGE                               uint32 = 281
	AVPCodeERRORREPORTINGHOST                         uint32 = 294
	AVPCodeEVENTTHRESHOLDEVENT1F                      uint32 = 1661
	AVPCodeEVENTTHRESHOLDEVENT1I                      uint32 = 1662
	AVPCodeEVENTTHRESHOLDRSRP                         uint32 = 1629
	AVPCodeEVENTTHRESHOLDRSRQ                         uint32 = 1630
	AVPCodeEVENTTIMESTAMP                             uint32 = 55
	AVPCodeEXPERIMENTALRESULT                         uint32 = 297
	AVPCodeEXPERIMENTALRESULTCODE                     uint32 = 298
	AVPCodeEXPIRATIONDATE                             uint32 = 1439
	AVPCodeEXPIRYTIME                                 uint32 = 709
	AVPCodeEXTPDPADDRESS                              uint32 = 1244
	AVPCodeEXTPDPTYPE                                 uint32 = 1243
	AVPCodeEXTENDEDMAXREQUESTEDBWDL                   uint32 = 553
	AVPCodeEXTENDEDMAXREQUESTEDBWUL                   uint32 = 554
	AVPCodeEXTERNALCLIENT                             uint32 = 1479
	AVPCodeEXTERNALIDENTIFIER                         uint32 = 3111
	AVPCodeFAILEDAVP                                  uint32 = 279
	AVPCodeFEATURELIST                                uint32 = 630
	AVPCodeFEATURELISTID                              uint32 = 629
	AVPCodeFIRMWAREREVISION                           uint32 = 267
	AVPCodeFROMSIPHEADER                              uint32 = 644
	AVPCodeGERANVECTOR                                uint32 = 1416
	AVPCodeGMLCADDRESS                                uint32 = 1474
	AVPCodeGMLCRESTRICTION                            uint32 = 1481
	AVPCodeGPRSSUBSCRIPTIONDATA                       uint32 = 1467
	AVPCodeGROUPPLMNID                                uint32 = 1677
	AVPCodeGROUPSERVICEID                             uint32 = 1676
	AVPCodeHPLMNODB                                   uint32 = 1418
	AVPCodeHOMOGENEOUSSUPPORTOFIMSVOICEOVERPSSESSIONS uint32 = 1493
	AVPCodeHOSTIPADDRESS                              uint32 = 257
	AVPCodeICSINDICATOR                               uint32 = 1491
	AVPCodeIDAFLAGS                                   uint32 = 1441
	AVPCodeIDRFLAGS                                   uint32 = 1490
	AVPCodeIMEI                                       uint32 = 1402
	AVPCodeIMSVOICEOVERPSSESSIONSSUPPORTED            uint32 = 1492
	AVPCodeIMSIGROUPID                                uint32 = 1675
	AVPCodeIDENTITYSET                                uint32 = 708
	AVPCodeIDENTITYWITHEMERGENCYREGISTRATION          uint32 = 651
	AVPCodeIMMEDIATERESPONSEPREFERRED                 uint32 = 1412
	AVPCodeINBANDSECURITYID                           uint32 = 299
	AVPCodeINTEGRITYKEY                               uint32 = 1452
	AVPCodeITEMNUMBER                                 uint32 = 1419
	AVPCodeJOBTYPE                                    uint32 = 1623
	AVPCodeKASME                                      uint32 = 1450
	AVPCodeKC                                         uint32 = 1453
	AVPCodeLCSINFO                                    uint32 = 1473
	AVPCodeLCSPRIVACYEXCEPTION                        uint32 = 1475
	AVPCodeLIPAPERMISSION                             uint32 = 1618
	AVPCodeLASTUEACTIVITYTIME                         uint32 = 1494
	AVPCodeLINEIDENTIFIER                             uint32 = 500
	AVPCodeLISTOFMEASUREMENTS                         uint32 = 1625
	AVPCodeLOAD                                       uint32 = 651
	AVPCodeLOADTYPE                                   uint32 = 652
	AVPCodeLOADVALUE                                  uint32 = 653
	AVPCodeLOCALGROUPID                               uint32 = 1678
	AVPCodeLOCALTIMEZONE                              uint32 = 2346
	AVPCodeLOCALTIMEZONEINDICATION                    uint32 = 718
	AVPCodeLOGGINGDURATION                            uint32 = 1632
	AVPCodeLOGGINGINTERVAL                            uint32 = 1631
	AVPCodeLOOSEROUTEINDICATION                       uint32 = 638
	AVPCodeMDTCONFIGURATION                           uint32 = 1622
	AVPCodeMDTUSERCONSENT                             uint32 = 1634
	AVPCodeMIPHOMEAGENTADDRESS                        uint32 = 334
	AVPCodeMIPHOMEAGENTHOST                           uint32 = 348
	AVPCodeMIP6AGENTINFO                              uint32 = 486
	AVPCodeMIP6HOMELINKPREFIX                         uint32 = 125
	AVPCodeMMELOCATIONINFORMATION                     uint32 = 1600
	AVPCodeMMENUMBERFORMTSMS                          uint32 = 1645
	AVPCodeMMEUSERSTATE                               uint32 = 1498
	AVPCodeMOLR                                       uint32 = 1486
	AVPCodeMPSPRIORITY                                uint32 = 1616
	AVPCodeMSISDN                                     uint32 = 701
	AVPCodeMANDATORYCAPABILITY                        uint32 = 604
	AVPCodeMAXREQUESTEDBANDWIDTHDL                    uint32 = 515
	AVPCodeMAXREQUESTEDBANDWIDTHUL                    uint32 = 516
	AVPCodeMAXIMUMDETECTIONTIME                       uint32 = 3144
	AVPCodeMAXIMUMNUMBEROFREPORTS                     uint32 = 3143
	AVPCodeMAXIMUMUEAVAILABILITYTIME                  uint32 = 3329
	AVPCodeMEASUREMENTPERIODLTE                       uint32 = 1656
	AVPCodeMEASUREMENTPERIODUMTS                      uint32 = 1655
	AVPCodeMEASUREMENTQUANTITY                        uint32 = 1660
	AVPCodeMONITORINGDURATION                         uint32 = 3130
	AVPCodeMONITORINGEVENTCONFIGSTATUS                uint32 = 3172
	AVPCodeMONITORINGEVENTCONFIGURATION               uint32 = 3142
	AVPCodeMONITORINGEVENTREPORT                      uint32 = 3155
	AVPCodeMONITORINGTYPE                             uint32 = 3141
	AVPCodeMULTIROUNDTIMEOUT                          uint32 = 272
	AVPCodeMULTIPLEREGISTRATIONINDICATION             uint32 = 648
	AVPCodeNORFLAGS                                   uint32 = 1443
	AVPCodeNETWORKACCESSMODE                          uint32 = 1417
	AVPCodeNONIPDATADELIVERYMECHANISM                 uint32 = 1682
	AVPCodeNONIPPDNTYPEINDICATOR                      uint32 = 1681
	AVPCodeNOTIFICATIONTOUEUSER                       uint32 = 1478
	AVPCodeNUMBEROFREQUESTEDVECTORS                   uint32 = 1410
	AVPCodeNUMBEROFUEPERLOCATIONCONFIGURATION         uint32 = 3306
	AVPCodeOCFEATUREVECTOR                            uint32 = 622
	AVPCodeOCOLR                                      uint32 = 623
	AVPCodeOCREDUCTIONPERCENTAGE                      uint32 = 626
	AVPCodeOCREPORTTYPE                               uint32 = 625
	AVPCodeOCSEQUENCENUMBER                           uint32 = 624
	AVPCodeOCSUPPORTEDFEATURES                        uint32 = 621
	AVPCodeOCVALIDITYDURATION                         uint32 = 627
	AVPCodeOMCID                                      uint32 = 1466
	AVPCodeONETIMENOTIFICATION                        uint32 = 712
	AVPCodeOPERATORDETERMINEDBARRING                  uint32 = 1425
	AVPCodeOPTIONALCAPABILITY                         uint32 = 605
	AVPCodeORIGINHOST                                 uint32 = 264
	AVPCodeORIGINREALM                                uint32 = 296
	AVPCodeORIGINSTATEID                              uint32 = 278
	AVPCodeORIGINATINGREQUEST                         uint32 = 633
	AVPCodePDNCONNECTIONCONTINUITY                    uint32 = 1690
	AVPCodePDNGWALLOCATIONTYPE                        uint32 = 1438
	AVPCodePDNTYPE                                    uint32 = 1456
	AVPCodePDPADDRESS                                 uint32 = 1227
	AVPCodePDPCONTEXT                                 uint32 = 1469
	AVPCodePDPTYPE                                    uint32 = 1470
	AVPCodePLMNCLIENT                                 uint32 = 1482
	AVPCodePLMNID                                     uint32 = 1500
	AVPCodePPRFLAGS                                   uint32 = 659
	AVPCodePUAFLAGS                                   uint32 = 1442
	AVPCodePURFLAGS                                   uint32 = 1635
	AVPCodePASSWORD                                   uint32 = 258
	AVPCodePATH                                       uint32 = 640
	AVPCodePERIODICCOMMUNICATIONINDICATOR             uint32 = 3120
	AVPCodePERIODICTIME                               uint32 = 3115
	AVPCodePOSITIONINGMETHOD                          uint32 = 1659
	AVPCodePREPAGINGSUPPORTED                         uint32 = 717
	AVPCodePREEMPTIONCAPABILITY                       uint32 = 1047
	AVPCodePREEMPTIONVULNERABILITY                    uint32 = 1048
	AVPCodePREFERREDDATAMODE                          uint32 = 1686
	AVPCodePRIMARYCHARGINGCOLLECTIONFUNCTIONNAME      uint32 = 621
	AVPCodePRIMARYEVENTCHARGINGFUNCTIONNAME           uint32 = 619
	AVPCodePRIORITYLEVEL                              uint32 = 1046
	AVPCodePROSEPERMISSION                            uint32 = 3819
	AVPCodePROSESUBSCRIPTIONDATA                      uint32 = 3818
	AVPCodePRODUCTNAME                                uint32 = 269
	AVPCodePROXYHOST                                  uint32 = 280
	AVPCodePROXYINFO                                  uint32 = 284
	AVPCodePROXYSTATE                                 uint32 = 33
	AVPCodePUBLICIDENTITY                             uint32 = 601
	AVPCodeQOSCLASSIDENTIFIER                         uint32 = 1028
	AVPCodeQOSSUBSCRIBED                              uint32 = 1404
	AVPCodeRAND                                       uint32 = 1447
	AVPCodeRATFREQUENCYSELECTIONPRIORITYID            uint32 = 1440
	AVPCodeRATTYPE                                    uint32 = 1032
	AVPCodeREAUTHREQUESTTYPE                          uint32 = 285
	AVPCodeRESYNCHRONIZATIONINFO                      uint32 = 1411
	AVPCodeREACHABILITYINFORMATION                    uint32 = 3164
	AVPCodeREASONCODE                                 uint32 = 616
	AVPCodeREASONINFO                                 uint32 = 617
	AVPCodeRECORDROUTE                                uint32 = 646
	AVPCodeREDIRECTHOST                               uint32 = 292
	AVPCodeREDIRECTHOSTUSAGE                          uint32 = 261
	AVPCodeREDIRECTMAXCACHETIME                       uint32 = 262
	AVPCodeREFERENCEIDVALIDITYTIME                    uint32 = 3118
	AVPCodeREGIONALSUBSCRIPTIONZONECODE               uint32 = 1446
	AVPCodeRELAYNODEINDICATOR                         uint32 = 1633
	AVPCodeREPORTAMOUNT                               uint32 = 1628
	AVPCodeREPORTINTERVAL                             uint32 = 1627
	AVPCodeREPORTINGTRIGGER                           uint32 = 1626
	AVPCodeREPOSITORYDATAID                           uint32 = 715
	AVPCodeREQUESTEDDOMAIN                            uint32 = 706
	AVPCodeREQUESTEDEUTRANAUTHENTICATIONINFO          uint32 = 1408
	AVPCodeREQUESTEDNODES                             uint32 = 713
	AVPCodeREQUESTEDUTRANGERANAUTHENTICATIONINFO      uint32 = 1409
	AVPCodeRESETID                                    uint32 = 1602
	AVPCodeRESTORATIONINFO                            uint32 = 649
	AVPCodeRESTORATIONPRIORITY                        uint32 = 1663
	AVPCodeRESULTCODE                                 uint32 = 268
	AVPCodeROAMINGRESTRICTEDDUETOUNSUPPORTEDFEATURE   uint32 = 1457
	AVPCodeROUTERECORD                                uint32 = 282
	AVPCodeSCEFID                                     uint32 = 3125
	AVPCodeSCEFREALM                                  uint32 = 1684
	AVPCodeSCEFREFERENCEID                            uint32 = 3123
	AVPCodeSCSCFRESTORATIONINFO                       uint32 = 639
	AVPCodeSGSNLOCATIONINFORMATION                    uint32 = 1601
	AVPCodeSGSNNUMBER                                 uint32 = 1489
	AVPCodeSGSNUSERSTATE                              uint32 = 1499
	AVPCodeSGSMMEIDENTITY                             uint32 = 1664
	AVPCodeSIPAUTHDATAITEM                            uint32 = 612
	AVPCodeSIPAUTHENTICATE                            uint32 = 609
	AVPCodeSIPAUTHENTICATIONCONTEXT                   uint32 = 611
	AVPCodeSIPAUTHENTICATIONSCHEME                    uint32 = 608
	AVPCodeSIPAUTHORIZATION                           uint32 = 610
	AVPCodeSIPDIGESTAUTHENTICATE                      uint32 = 635
	AVPCodeSIPITEMNUMBER                              uint32 = 613
	AVPCodeSIPNUMBERAUTHITEMS                         uint32 = 607
	AVPCodeSIPTOLOCALNETWORKPERMISSION                uint32 = 1665
	AVPCodeSIPTOPERMISSION                            uint32 = 1613
	AVPCodeSMSREGISTERREQUEST                         uint32 = 1648
	AVPCodeSRES                                       uint32 = 1454
	AVPCodeSSCODE                                     uint32 = 1476
	AVPCodeSSSTATUS                                   uint32 = 1477
	AVPCodeSTNSR                                      uint32 = 1433
	AVPCodeSCHEDULEDCOMMUNICATIONTIME                 uint32 = 3116
	AVPCodeSECONDARYCHARGINGCOLLECTIONFUNCTIONNAME    uint32 = 622
	AVPCodeSECONDARYEVENTCHARGINGFUNCTIONNAME         uint32 = 620
	AVPCodeSENDDATAINDICATION                         uint32 = 710
	AVPCodeSEQUENCENUMBER                             uint32 = 716
	AVPCodeSERVEDPARTYIPADDRESS                       uint32 = 848
	AVPCodeSERVERASSIGNMENTTYPE                       uint32 = 614
	AVPCodeSERVERCAPABILITIES                         uint32 = 603
	AVPCodeSERVERNAME                                 uint32 = 602
	AVPCodeSERVICEGAPTIME                             uint32 = 1698
	AVPCodeSERVICEINDICATION                          uint32 = 704
	AVPCodeSERVICESELECTION                           uint32 = 493
	AVPCodeSERVICETYPE                                uint32 = 1483
	AVPCodeSERVICETYPEIDENTITY                        uint32 = 1484
	AVPCodeSERVINGNODEINDICATION                      uint32 = 714
	AVPCodeSERVINGPLMNRATECONTROL                     uint32 = 4310
	AVPCodeSESSIONBINDING                             uint32 = 270
	AVPCodeSESSIONID                                  uint32 = 263
	AVPCodeSESSIONPRIORITY                            uint32 = 650
	AVPCodeSESSIONSERVERFAILOVER                      uint32 = 271
	AVPCodeSESSIONTIMEOUT                             uint32 = 27
	AVPCodeSOFTWAREVERSION                            uint32 = 1403
	AVPCodeSOURCEID                                   uint32 = 649
	AVPCodeSPECIFICAPNINFO                            uint32 = 1472
	AVPCodeSTATIONARYINDICATION                       uint32 = 3117
	AVPCodeSUBSREQTYPE                                uint32 = 705
	AVPCodeSUBSCRIBEDPERIODICRAUTAUTIMER              uint32 = 1619
	AVPCodeSUBSCRIBEDVSRVCC                           uint32 = 1636
	AVPCodeSUBSCRIBERSTATUS                           uint32 = 1424
	AVPCodeSUBSCRIPTIONDATA                           uint32 = 1400
	AVPCodeSUBSCRIPTIONDATADELETION                   uint32 = 1611
	AVPCodeSUBSCRIPTIONDATAFLAGS                      uint32 = 1654
	AVPCodeSUBSCRIPTIONINFO                           uint32 = 642
	AVPCodeSUPPORTEDFEATURES                          uint32 = 628
	AVPCodeSUPPORTEDMONITORINGEVENTS                  uint32 = 3144
	AVPCodeSUPPORTEDSERVICES                          uint32 = 3143
	AVPCodeSUPPORTEDVENDORID                          uint32 = 265
	AVPCodeTSCODE                                     uint32 = 1487
	AVPCodeTELESERVICELIST                            uint32 = 1485
	AVPCodeTERMINALINFORMATION                        uint32 = 1401
	AVPCodeTERMINATIONCAUSE                           uint32 = 295
	AVPCodeTIMEZONE                                   uint32 = 2349
	AVPCodeTOSIPHEADER                                uint32 = 645
	AVPCodeTRACECOLLECTIONENTITY                      uint32 = 1468
	AVPCodeTRACEDATA                                  uint32 = 1458
	AVPCodeTRACEDEPTH                                 uint32 = 1462
	AVPCodeTRACEEVENTLIST                             uint32 = 1465
	AVPCodeTRACEINTERFACELIST                         uint32 = 1464
	AVPCodeTRACENETYPELIST                            uint32 = 1463
	AVPCodeTRACEREFERENCE                             uint32 = 1459
	AVPCodeUARFLAGS                                   uint32 = 637
	AVPCodeUDRFLAGS                                   uint32 = 719
	AVPCodeUEPC5AMBR                                  uint32 = 3803
	AVPCodeUEREACHABILITYCONFIGURATION                uint32 = 3145
	AVPCodeUESRVCCCAPABILITY                          uint32 = 1615
	AVPCodeUEUSAGETYPE                                uint32 = 1680
	AVPCodeULAFLAGS                                   uint32 = 1406
	AVPCodeULRFLAGS                                   uint32 = 1405
	AVPCodeUTRANVECTOR                                uint32 = 1415
	AVPCodeUSERAUTHORIZATIONTYPE                      uint32 = 623
	AVPCodeUSERDATA                                   uint32 = 702
	AVPCodeUSERDATAALREADYAVAILABLE                   uint32 = 624
	AVPCodeUSERID                                     uint32 = 1745
	AVPCodeUSERIDENTITY                               uint32 = 700
	AVPCodeUSERNAME                                   uint32 = 1
	AVPCodeV2XPC5QOSFLOW                              uint32 = 3805
	AVPCodeV2XPC5QOSPARAMETERS                        uint32 = 3804
	AVPCodeV2XPERMISSION                              uint32 = 3802
	AVPCodeV2XSUBSCRIPTIONDATA                        uint32 = 3801
	AVPCodeVPLMNDYNAMICADDRESSALLOWED                 uint32 = 1432
	AVPCodeVPLMNLIPAALLOWED                           uint32 = 1617
	AVPCodeVENDORID                                   uint32 = 266
	AVPCodeVENDORSPECIFICAPPLICATIONID                uint32 = 260
	AVPCodeVISITEDNETWORKIDENTIFIER                   uint32 = 600
	AVPCodeVISITEDPLMNID                              uint32 = 1407
	AVPCodeWLANOFFLOADABILITY                         uint32 = 1667
	AVPCodeWLANOFFLOADABILITYEUTRAN                   uint32 = 1668
	AVPCodeWLANOFFLOADABILITYUTRAN                    uint32 = 1669
	AVPCodeWILDCARDEDIMPU                             uint32 = 636
	AVPCodeWILDCARDEDPUBLICIDENTITY                   uint32 = 634
	AVPCodeWRONGPASSWORDATTEMPTSCOUNTER               uint32 = 1492
	AVPCodeXRES                                       uint32 = 1448
	AVPCodeEDRXCYCLELENGTH                            uint32 = 1691
	AVPCodeEDRXCYCLELENGTHVALUE                       uint32 = 1694
	AVPCodeEDRXRELATEDRAT                             uint32 = 1705
)

// Vendor IDs
const (
	VendorID10415 uint32 = 10415
	VendorID13019 uint32 = 13019
)

// Command Codes
const (
	CommandCodeLOCATIONINFOANSWER             uint32 = 302
	CommandCodeLOCATIONINFOREQUEST            uint32 = 302
	CommandCodeMULTIMEDIAAUTHANSWER           uint32 = 303
	CommandCodeMULTIMEDIAAUTHREQUEST          uint32 = 303
	CommandCodePUSHPROFILEANSWER              uint32 = 305
	CommandCodePUSHPROFILEREQUEST             uint32 = 305
	CommandCodeREGISTRATIONTERMINATIONANSWER  uint32 = 304
	CommandCodeREGISTRATIONTERMINATIONREQUEST uint32 = 304
	CommandCodeSERVERASSIGNMENTANSWER         uint32 = 301
	CommandCodeSERVERASSIGNMENTREQUEST        uint32 = 301
	CommandCodeUSERAUTHORIZATIONANSWER        uint32 = 300
	CommandCodeUSERAUTHORIZATIONREQUEST       uint32 = 300
)

// EmergencyRegistrationResult represents the EmergencyRegistrationResult enumerated type
type EmergencyRegistrationResult uint32

// EmergencyRegistrationResult values
const (
	EmergencyRegistrationResult_EMERGENCY_REGISTRATION     EmergencyRegistrationResult = 0
	EmergencyRegistrationResult_IMS_EMERGENCY_REGISTRATION EmergencyRegistrationResult = 1
)

// LooseRouteIndication represents the LooseRouteIndication enumerated type
type LooseRouteIndication uint32

// LooseRouteIndication values
const (
	LooseRouteIndication_LOOSE_ROUTE_NOT_REQUIRED LooseRouteIndication = 0
	LooseRouteIndication_LOOSE_ROUTE_REQUIRED     LooseRouteIndication = 1
)

// MultipleRegistrationIndication represents the MultipleRegistrationIndication enumerated type
type MultipleRegistrationIndication uint32

// MultipleRegistrationIndication values
const (
	MultipleRegistrationIndication_MULTIPLE_REGISTRATION     MultipleRegistrationIndication = 1
	MultipleRegistrationIndication_NOT_MULTIPLE_REGISTRATION MultipleRegistrationIndication = 0
)

// OriginatingRequest represents the OriginatingRequest enumerated type
type OriginatingRequest uint32

// OriginatingRequest values
const (
	OriginatingRequest_ORIGINATING OriginatingRequest = 0
)

// ReasonCode represents the ReasonCode enumerated type
type ReasonCode uint32

// ReasonCode values
const (
	ReasonCode_NEW_SERVER_ASSIGNED   ReasonCode = 1
	ReasonCode_PERMANENT_TERMINATION ReasonCode = 0
	ReasonCode_REMOVE_S_CSCF         ReasonCode = 3
	ReasonCode_SERVER_CHANGE         ReasonCode = 2
)

// ServerAssignmentType represents the ServerAssignmentType enumerated type
type ServerAssignmentType uint32

// ServerAssignmentType values
const (
	ServerAssignmentType_ADMINISTRATIVE_DEREGISTRATION            ServerAssignmentType = 8
	ServerAssignmentType_AUTHENTICATION_FAILURE                   ServerAssignmentType = 9
	ServerAssignmentType_AUTHENTICATION_TIMEOUT                   ServerAssignmentType = 10
	ServerAssignmentType_DEREGISTRATION_TOO_MUCH_DATA             ServerAssignmentType = 11
	ServerAssignmentType_NO_ASSIGNMENT                            ServerAssignmentType = 0
	ServerAssignmentType_REGISTRATION                             ServerAssignmentType = 1
	ServerAssignmentType_RE_REGISTRATION                          ServerAssignmentType = 2
	ServerAssignmentType_TIMEOUT_DEREGISTRATION                   ServerAssignmentType = 4
	ServerAssignmentType_TIMEOUT_DEREGISTRATION_STORE_SERVER_NAME ServerAssignmentType = 6
	ServerAssignmentType_UNREGISTERED_USER                        ServerAssignmentType = 3
	ServerAssignmentType_USER_DEREGISTRATION                      ServerAssignmentType = 5
	ServerAssignmentType_USER_DEREGISTRATION_STORE_SERVER_NAME    ServerAssignmentType = 7
)

// SessionPriority represents the SessionPriority enumerated type
type SessionPriority uint32

// SessionPriority values
const (
	SessionPriority_PRIORITY_0 SessionPriority = 0
	SessionPriority_PRIORITY_1 SessionPriority = 1
	SessionPriority_PRIORITY_2 SessionPriority = 2
	SessionPriority_PRIORITY_3 SessionPriority = 3
	SessionPriority_PRIORITY_4 SessionPriority = 4
)

// UserAuthorizationType represents the UserAuthorizationType enumerated type
type UserAuthorizationType uint32

// UserAuthorizationType values
const (
	UserAuthorizationType_DE_REGISTRATION               UserAuthorizationType = 1
	UserAuthorizationType_REGISTRATION                  UserAuthorizationType = 0
	UserAuthorizationType_REGISTRATION_AND_CAPABILITIES UserAuthorizationType = 2
)

// UserDataAlreadyAvailable represents the UserDataAlreadyAvailable enumerated type
type UserDataAlreadyAvailable uint32

// UserDataAlreadyAvailable values
const (
	UserDataAlreadyAvailable_USER_DATA_ALREADY_AVAILABLE UserDataAlreadyAvailable = 1
	UserDataAlreadyAvailable_USER_DATA_NOT_AVAILABLE     UserDataAlreadyAvailable = 0
)
