// Code generated by diameter-codegen. DO NOT EDIT.

package cx

import (
	"bytes"
	"testing"

	"github.com/hsdfat/diam-gw/models_base"
)

// TestUserAuthorizationRequest_Creation tests basic creation and initialization
func TestUserAuthorizationRequest_Creation(t *testing.T) {
	msg := NewUserAuthorizationRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 300 {
		t.Errorf("Expected command code 300, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestUserAuthorizationRequest_Validation tests field validation
func TestUserAuthorizationRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &UserAuthorizationRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewUserAuthorizationRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.PublicIdentity = models_base.UTF8String("452040000000010")
		msg.VisitedNetworkIdentifier = models_base.OctetString([]byte{0x01, 0x02, 0x03})

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestUserAuthorizationRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestUserAuthorizationRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewUserAuthorizationRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.PublicIdentity = models_base.UTF8String("452040000000010")
	original.VisitedNetworkIdentifier = models_base.OctetString([]byte{0x01, 0x02, 0x03})

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &UserAuthorizationRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}
	if decoded.PublicIdentity != original.PublicIdentity {
		t.Errorf("PublicIdentity mismatch: got %v, want %v", decoded.PublicIdentity, original.PublicIdentity)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestUserAuthorizationAnswer_Creation tests basic creation and initialization
func TestUserAuthorizationAnswer_Creation(t *testing.T) {
	msg := NewUserAuthorizationAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 300 {
		t.Errorf("Expected command code 300, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestUserAuthorizationAnswer_Validation tests field validation
func TestUserAuthorizationAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &UserAuthorizationAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewUserAuthorizationAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestUserAuthorizationAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestUserAuthorizationAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewUserAuthorizationAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &UserAuthorizationAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestServerAssignmentRequest_Creation tests basic creation and initialization
func TestServerAssignmentRequest_Creation(t *testing.T) {
	msg := NewServerAssignmentRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 301 {
		t.Errorf("Expected command code 301, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestServerAssignmentRequest_Validation tests field validation
func TestServerAssignmentRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &ServerAssignmentRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewServerAssignmentRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.ServerName = models_base.UTF8String("452040000000010")
		msg.ServerAssignmentType = models_base.Enumerated(1)

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestServerAssignmentRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestServerAssignmentRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewServerAssignmentRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.ServerName = models_base.UTF8String("452040000000010")
	original.ServerAssignmentType = models_base.Enumerated(1)

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &ServerAssignmentRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.ServerName != original.ServerName {
		t.Errorf("ServerName mismatch: got %v, want %v", decoded.ServerName, original.ServerName)
	}
	if decoded.ServerAssignmentType != original.ServerAssignmentType {
		t.Errorf("ServerAssignmentType mismatch: got %d, want %d", decoded.ServerAssignmentType, original.ServerAssignmentType)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestServerAssignmentAnswer_Creation tests basic creation and initialization
func TestServerAssignmentAnswer_Creation(t *testing.T) {
	msg := NewServerAssignmentAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 301 {
		t.Errorf("Expected command code 301, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestServerAssignmentAnswer_Validation tests field validation
func TestServerAssignmentAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &ServerAssignmentAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewServerAssignmentAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestServerAssignmentAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestServerAssignmentAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewServerAssignmentAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &ServerAssignmentAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestLocationInfoRequest_Creation tests basic creation and initialization
func TestLocationInfoRequest_Creation(t *testing.T) {
	msg := NewLocationInfoRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 302 {
		t.Errorf("Expected command code 302, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestLocationInfoRequest_Validation tests field validation
func TestLocationInfoRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &LocationInfoRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewLocationInfoRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.OriginatingRequest = models_base.Enumerated(1)
		msg.PublicIdentity = models_base.UTF8String("452040000000010")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestLocationInfoRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestLocationInfoRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewLocationInfoRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.OriginatingRequest = models_base.Enumerated(1)
	original.PublicIdentity = models_base.UTF8String("452040000000010")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &LocationInfoRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.OriginatingRequest != original.OriginatingRequest {
		t.Errorf("OriginatingRequest mismatch: got %d, want %d", decoded.OriginatingRequest, original.OriginatingRequest)
	}
	if decoded.PublicIdentity != original.PublicIdentity {
		t.Errorf("PublicIdentity mismatch: got %v, want %v", decoded.PublicIdentity, original.PublicIdentity)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestLocationInfoAnswer_Creation tests basic creation and initialization
func TestLocationInfoAnswer_Creation(t *testing.T) {
	msg := NewLocationInfoAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 302 {
		t.Errorf("Expected command code 302, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestLocationInfoAnswer_Validation tests field validation
func TestLocationInfoAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &LocationInfoAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewLocationInfoAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestLocationInfoAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestLocationInfoAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewLocationInfoAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &LocationInfoAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestMultimediaAuthRequest_Creation tests basic creation and initialization
func TestMultimediaAuthRequest_Creation(t *testing.T) {
	msg := NewMultimediaAuthRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 303 {
		t.Errorf("Expected command code 303, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestMultimediaAuthRequest_Validation tests field validation
func TestMultimediaAuthRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &MultimediaAuthRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewMultimediaAuthRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.PublicIdentity = models_base.UTF8String("452040000000010")
		msg.SipAuthDataItem = &SIPAuthDataItem{
			SipItemNumber:           ptrUnsigned32(1),
			SipAuthenticationScheme: ptrUTF8String("test"),
			SipAuthenticate:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
			// ... and 6 more fields
		}
		msg.SipNumberAuthItems = models_base.Unsigned32(1)
		msg.ServerName = models_base.UTF8String("452040000000010")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestMultimediaAuthRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestMultimediaAuthRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewMultimediaAuthRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.PublicIdentity = models_base.UTF8String("452040000000010")
	original.SipAuthDataItem = &SIPAuthDataItem{
		SipItemNumber:           ptrUnsigned32(1),
		SipAuthenticationScheme: ptrUTF8String("test"),
		SipAuthenticate:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
		// ... and 6 more fields
	}
	original.SipNumberAuthItems = models_base.Unsigned32(1)
	original.ServerName = models_base.UTF8String("452040000000010")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &MultimediaAuthRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}
	if decoded.PublicIdentity != original.PublicIdentity {
		t.Errorf("PublicIdentity mismatch: got %v, want %v", decoded.PublicIdentity, original.PublicIdentity)
	}
	if decoded.SipNumberAuthItems != original.SipNumberAuthItems {
		t.Errorf("SipNumberAuthItems mismatch: got %d, want %d", decoded.SipNumberAuthItems, original.SipNumberAuthItems)
	}
	if decoded.ServerName != original.ServerName {
		t.Errorf("ServerName mismatch: got %v, want %v", decoded.ServerName, original.ServerName)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestMultimediaAuthAnswer_Creation tests basic creation and initialization
func TestMultimediaAuthAnswer_Creation(t *testing.T) {
	msg := NewMultimediaAuthAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 303 {
		t.Errorf("Expected command code 303, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestMultimediaAuthAnswer_Validation tests field validation
func TestMultimediaAuthAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &MultimediaAuthAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewMultimediaAuthAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestMultimediaAuthAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestMultimediaAuthAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewMultimediaAuthAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &MultimediaAuthAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestRegistrationTerminationRequest_Creation tests basic creation and initialization
func TestRegistrationTerminationRequest_Creation(t *testing.T) {
	msg := NewRegistrationTerminationRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 304 {
		t.Errorf("Expected command code 304, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestRegistrationTerminationRequest_Validation tests field validation
func TestRegistrationTerminationRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &RegistrationTerminationRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewRegistrationTerminationRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationHost = models_base.DiameterIdentity("server.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.DeregistrationReason = &DeregistrationReason{
			ReasonCode: models_base.Enumerated(1),
			ReasonInfo: ptrUTF8String("test"),
		}

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestRegistrationTerminationRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestRegistrationTerminationRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewRegistrationTerminationRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationHost = models_base.DiameterIdentity("server.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.DeregistrationReason = &DeregistrationReason{
		ReasonCode: models_base.Enumerated(1),
		ReasonInfo: ptrUTF8String("test"),
	}

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &RegistrationTerminationRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationHost != original.DestinationHost {
		t.Errorf("DestinationHost mismatch: got %v, want %v", decoded.DestinationHost, original.DestinationHost)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestRegistrationTerminationAnswer_Creation tests basic creation and initialization
func TestRegistrationTerminationAnswer_Creation(t *testing.T) {
	msg := NewRegistrationTerminationAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 304 {
		t.Errorf("Expected command code 304, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestRegistrationTerminationAnswer_Validation tests field validation
func TestRegistrationTerminationAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &RegistrationTerminationAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewRegistrationTerminationAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestRegistrationTerminationAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestRegistrationTerminationAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewRegistrationTerminationAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &RegistrationTerminationAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestPushProfileRequest_Creation tests basic creation and initialization
func TestPushProfileRequest_Creation(t *testing.T) {
	msg := NewPushProfileRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 305 {
		t.Errorf("Expected command code 305, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestPushProfileRequest_Validation tests field validation
func TestPushProfileRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &PushProfileRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewPushProfileRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationHost = models_base.DiameterIdentity("server.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestPushProfileRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestPushProfileRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewPushProfileRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationHost = models_base.DiameterIdentity("server.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &PushProfileRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationHost != original.DestinationHost {
		t.Errorf("DestinationHost mismatch: got %v, want %v", decoded.DestinationHost, original.DestinationHost)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestPushProfileAnswer_Creation tests basic creation and initialization
func TestPushProfileAnswer_Creation(t *testing.T) {
	msg := NewPushProfileAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 305 {
		t.Errorf("Expected command code 305, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777216 {
		t.Errorf("Expected application ID 16777216, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestPushProfileAnswer_Validation tests field validation
func TestPushProfileAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &PushProfileAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewPushProfileAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestPushProfileAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestPushProfileAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewPushProfileAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &PushProfileAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}
