// Code generated by diameter-codegen. DO NOT EDIT.

package sh

import (
	"bytes"
	"testing"

	"github.com/hsdfat/diam-gw/models_base"
)

// TestUserDataRequest_Creation tests basic creation and initialization
func TestUserDataRequest_Creation(t *testing.T) {
	msg := NewUserDataRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 306 {
		t.Errorf("Expected command code 306, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestUserDataRequest_Validation tests field validation
func TestUserDataRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &UserDataRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewUserDataRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserIdentity = &UserIdentity{
			PublicIdentity: ptrUTF8String("test"),
			Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
		}
		msg.DataReference = []models_base.Enumerated{models_base.Enumerated(1)}

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestUserDataRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestUserDataRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewUserDataRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserIdentity = &UserIdentity{
		PublicIdentity: ptrUTF8String("test"),
		Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
	}
	original.DataReference = []models_base.Enumerated{models_base.Enumerated(1)}

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &UserDataRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestUserDataAnswer_Creation tests basic creation and initialization
func TestUserDataAnswer_Creation(t *testing.T) {
	msg := NewUserDataAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 306 {
		t.Errorf("Expected command code 306, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestUserDataAnswer_Validation tests field validation
func TestUserDataAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &UserDataAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewUserDataAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestUserDataAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestUserDataAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewUserDataAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &UserDataAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestProfileUpdateRequest_Creation tests basic creation and initialization
func TestProfileUpdateRequest_Creation(t *testing.T) {
	msg := NewProfileUpdateRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 307 {
		t.Errorf("Expected command code 307, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestProfileUpdateRequest_Validation tests field validation
func TestProfileUpdateRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &ProfileUpdateRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewProfileUpdateRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserIdentity = &UserIdentity{
			PublicIdentity: ptrUTF8String("test"),
			Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
		}
		msg.DataReference = []models_base.Enumerated{models_base.Enumerated(1)}
		msg.UserData = models_base.OctetString([]byte{0x01, 0x02, 0x03})

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestProfileUpdateRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestProfileUpdateRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewProfileUpdateRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserIdentity = &UserIdentity{
		PublicIdentity: ptrUTF8String("test"),
		Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
	}
	original.DataReference = []models_base.Enumerated{models_base.Enumerated(1)}
	original.UserData = models_base.OctetString([]byte{0x01, 0x02, 0x03})

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &ProfileUpdateRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestProfileUpdateAnswer_Creation tests basic creation and initialization
func TestProfileUpdateAnswer_Creation(t *testing.T) {
	msg := NewProfileUpdateAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 307 {
		t.Errorf("Expected command code 307, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestProfileUpdateAnswer_Validation tests field validation
func TestProfileUpdateAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &ProfileUpdateAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewProfileUpdateAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestProfileUpdateAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestProfileUpdateAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewProfileUpdateAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &ProfileUpdateAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestSubscribeNotificationsRequest_Creation tests basic creation and initialization
func TestSubscribeNotificationsRequest_Creation(t *testing.T) {
	msg := NewSubscribeNotificationsRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 308 {
		t.Errorf("Expected command code 308, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestSubscribeNotificationsRequest_Validation tests field validation
func TestSubscribeNotificationsRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &SubscribeNotificationsRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewSubscribeNotificationsRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserIdentity = &UserIdentity{
			PublicIdentity: ptrUTF8String("test"),
			Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
		}
		msg.SubsReqType = models_base.Enumerated(1)
		msg.DataReference = []models_base.Enumerated{models_base.Enumerated(1)}

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestSubscribeNotificationsRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestSubscribeNotificationsRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewSubscribeNotificationsRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserIdentity = &UserIdentity{
		PublicIdentity: ptrUTF8String("test"),
		Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
	}
	original.SubsReqType = models_base.Enumerated(1)
	original.DataReference = []models_base.Enumerated{models_base.Enumerated(1)}

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &SubscribeNotificationsRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.SubsReqType != original.SubsReqType {
		t.Errorf("SubsReqType mismatch: got %d, want %d", decoded.SubsReqType, original.SubsReqType)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestSubscribeNotificationsAnswer_Creation tests basic creation and initialization
func TestSubscribeNotificationsAnswer_Creation(t *testing.T) {
	msg := NewSubscribeNotificationsAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 308 {
		t.Errorf("Expected command code 308, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestSubscribeNotificationsAnswer_Validation tests field validation
func TestSubscribeNotificationsAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &SubscribeNotificationsAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewSubscribeNotificationsAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestSubscribeNotificationsAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestSubscribeNotificationsAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewSubscribeNotificationsAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &SubscribeNotificationsAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestPushNotificationRequest_Creation tests basic creation and initialization
func TestPushNotificationRequest_Creation(t *testing.T) {
	msg := NewPushNotificationRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 309 {
		t.Errorf("Expected command code 309, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestPushNotificationRequest_Validation tests field validation
func TestPushNotificationRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &PushNotificationRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewPushNotificationRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationHost = models_base.DiameterIdentity("server.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserIdentity = &UserIdentity{
			PublicIdentity: ptrUTF8String("test"),
			Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
		}

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestPushNotificationRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestPushNotificationRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewPushNotificationRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationHost = models_base.DiameterIdentity("server.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserIdentity = &UserIdentity{
		PublicIdentity: ptrUTF8String("test"),
		Msisdn:         ptrOctetString([]byte{0x01, 0x02, 0x03}),
	}

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &PushNotificationRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationHost != original.DestinationHost {
		t.Errorf("DestinationHost mismatch: got %v, want %v", decoded.DestinationHost, original.DestinationHost)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestPushNotificationAnswer_Creation tests basic creation and initialization
func TestPushNotificationAnswer_Creation(t *testing.T) {
	msg := NewPushNotificationAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 309 {
		t.Errorf("Expected command code 309, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777217 {
		t.Errorf("Expected application ID 16777217, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestPushNotificationAnswer_Validation tests field validation
func TestPushNotificationAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &PushNotificationAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewPushNotificationAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.VendorSpecificApplicationId = &VendorSpecificApplicationId{
			VendorId:          ptrUnsigned32(1),
			AuthApplicationId: ptrUnsigned32(1),
			AcctApplicationId: ptrUnsigned32(1),
		}
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestPushNotificationAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestPushNotificationAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewPushNotificationAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.VendorSpecificApplicationId = &VendorSpecificApplicationId{
		VendorId:          ptrUnsigned32(1),
		AuthApplicationId: ptrUnsigned32(1),
		AcctApplicationId: ptrUnsigned32(1),
	}
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &PushNotificationAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}
