// Code generated by diameter-codegen. DO NOT EDIT.

package s6a

import (
	"bytes"
	"testing"

	"github.com/hsdfat/diam-gw/models_base"
)

// TestUpdateLocationRequest_Creation tests basic creation and initialization
func TestUpdateLocationRequest_Creation(t *testing.T) {
	msg := NewUpdateLocationRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 316 {
		t.Errorf("Expected command code 316, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestUpdateLocationRequest_Validation tests field validation
func TestUpdateLocationRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &UpdateLocationRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewUpdateLocationRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.RatType = models_base.Enumerated(1)
		msg.UlrFlags = models_base.Unsigned32(1)
		msg.VisitedPlmnId = models_base.OctetString([]byte{0x00, 0xF1, 0x10})

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestUpdateLocationRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestUpdateLocationRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewUpdateLocationRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.RatType = models_base.Enumerated(1)
	original.UlrFlags = models_base.Unsigned32(1)
	original.VisitedPlmnId = models_base.OctetString([]byte{0x00, 0xF1, 0x10})

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &UpdateLocationRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}
	if decoded.RatType != original.RatType {
		t.Errorf("RatType mismatch: got %d, want %d", decoded.RatType, original.RatType)
	}
	if decoded.UlrFlags != original.UlrFlags {
		t.Errorf("UlrFlags mismatch: got %d, want %d", decoded.UlrFlags, original.UlrFlags)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestUpdateLocationAnswer_Creation tests basic creation and initialization
func TestUpdateLocationAnswer_Creation(t *testing.T) {
	msg := NewUpdateLocationAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 316 {
		t.Errorf("Expected command code 316, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestUpdateLocationAnswer_Validation tests field validation
func TestUpdateLocationAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &UpdateLocationAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewUpdateLocationAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestUpdateLocationAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestUpdateLocationAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewUpdateLocationAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &UpdateLocationAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestAuthenticationInformationRequest_Creation tests basic creation and initialization
func TestAuthenticationInformationRequest_Creation(t *testing.T) {
	msg := NewAuthenticationInformationRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 318 {
		t.Errorf("Expected command code 318, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestAuthenticationInformationRequest_Validation tests field validation
func TestAuthenticationInformationRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &AuthenticationInformationRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewAuthenticationInformationRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.VisitedPlmnId = models_base.OctetString([]byte{0x00, 0xF1, 0x10})

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestAuthenticationInformationRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestAuthenticationInformationRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewAuthenticationInformationRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.VisitedPlmnId = models_base.OctetString([]byte{0x00, 0xF1, 0x10})

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &AuthenticationInformationRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestAuthenticationInformationAnswer_Creation tests basic creation and initialization
func TestAuthenticationInformationAnswer_Creation(t *testing.T) {
	msg := NewAuthenticationInformationAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 318 {
		t.Errorf("Expected command code 318, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestAuthenticationInformationAnswer_Validation tests field validation
func TestAuthenticationInformationAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &AuthenticationInformationAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewAuthenticationInformationAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestAuthenticationInformationAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestAuthenticationInformationAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewAuthenticationInformationAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &AuthenticationInformationAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestCancelLocationRequest_Creation tests basic creation and initialization
func TestCancelLocationRequest_Creation(t *testing.T) {
	msg := NewCancelLocationRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 317 {
		t.Errorf("Expected command code 317, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestCancelLocationRequest_Validation tests field validation
func TestCancelLocationRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &CancelLocationRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewCancelLocationRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationHost = models_base.DiameterIdentity("server.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.CancellationType = models_base.Enumerated(1)

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestCancelLocationRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestCancelLocationRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewCancelLocationRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationHost = models_base.DiameterIdentity("server.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.CancellationType = models_base.Enumerated(1)

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &CancelLocationRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationHost != original.DestinationHost {
		t.Errorf("DestinationHost mismatch: got %v, want %v", decoded.DestinationHost, original.DestinationHost)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}
	if decoded.CancellationType != original.CancellationType {
		t.Errorf("CancellationType mismatch: got %d, want %d", decoded.CancellationType, original.CancellationType)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestCancelLocationAnswer_Creation tests basic creation and initialization
func TestCancelLocationAnswer_Creation(t *testing.T) {
	msg := NewCancelLocationAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 317 {
		t.Errorf("Expected command code 317, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestCancelLocationAnswer_Validation tests field validation
func TestCancelLocationAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &CancelLocationAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewCancelLocationAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestCancelLocationAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestCancelLocationAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewCancelLocationAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &CancelLocationAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestInsertSubscriberDataRequest_Creation tests basic creation and initialization
func TestInsertSubscriberDataRequest_Creation(t *testing.T) {
	msg := NewInsertSubscriberDataRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 319 {
		t.Errorf("Expected command code 319, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestInsertSubscriberDataRequest_Validation tests field validation
func TestInsertSubscriberDataRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &InsertSubscriberDataRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewInsertSubscriberDataRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationHost = models_base.DiameterIdentity("server.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.SubscriptionData = &SubscriptionData{
			SubscriberStatus: ptrEnumerated(1),
			Msisdn:           ptrOctetString([]byte{0x01, 0x02, 0x03}),
			AMsisdn:          ptrOctetString([]byte{0x01, 0x02, 0x03}),
			// ... and 42 more fields
		}

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestInsertSubscriberDataRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestInsertSubscriberDataRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewInsertSubscriberDataRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationHost = models_base.DiameterIdentity("server.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.SubscriptionData = &SubscriptionData{
		SubscriberStatus: ptrEnumerated(1),
		Msisdn:           ptrOctetString([]byte{0x01, 0x02, 0x03}),
		AMsisdn:          ptrOctetString([]byte{0x01, 0x02, 0x03}),
		// ... and 42 more fields
	}

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &InsertSubscriberDataRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationHost != original.DestinationHost {
		t.Errorf("DestinationHost mismatch: got %v, want %v", decoded.DestinationHost, original.DestinationHost)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestInsertSubscriberDataAnswer_Creation tests basic creation and initialization
func TestInsertSubscriberDataAnswer_Creation(t *testing.T) {
	msg := NewInsertSubscriberDataAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 319 {
		t.Errorf("Expected command code 319, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestInsertSubscriberDataAnswer_Validation tests field validation
func TestInsertSubscriberDataAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &InsertSubscriberDataAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewInsertSubscriberDataAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestInsertSubscriberDataAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestInsertSubscriberDataAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewInsertSubscriberDataAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &InsertSubscriberDataAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestDeleteSubscriberDataRequest_Creation tests basic creation and initialization
func TestDeleteSubscriberDataRequest_Creation(t *testing.T) {
	msg := NewDeleteSubscriberDataRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 320 {
		t.Errorf("Expected command code 320, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestDeleteSubscriberDataRequest_Validation tests field validation
func TestDeleteSubscriberDataRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &DeleteSubscriberDataRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewDeleteSubscriberDataRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationHost = models_base.DiameterIdentity("server.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")
		msg.DsrFlags = models_base.Unsigned32(1)

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestDeleteSubscriberDataRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestDeleteSubscriberDataRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewDeleteSubscriberDataRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationHost = models_base.DiameterIdentity("server.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")
	original.DsrFlags = models_base.Unsigned32(1)

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &DeleteSubscriberDataRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationHost != original.DestinationHost {
		t.Errorf("DestinationHost mismatch: got %v, want %v", decoded.DestinationHost, original.DestinationHost)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}
	if decoded.DsrFlags != original.DsrFlags {
		t.Errorf("DsrFlags mismatch: got %d, want %d", decoded.DsrFlags, original.DsrFlags)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestDeleteSubscriberDataAnswer_Creation tests basic creation and initialization
func TestDeleteSubscriberDataAnswer_Creation(t *testing.T) {
	msg := NewDeleteSubscriberDataAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 320 {
		t.Errorf("Expected command code 320, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestDeleteSubscriberDataAnswer_Validation tests field validation
func TestDeleteSubscriberDataAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &DeleteSubscriberDataAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewDeleteSubscriberDataAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestDeleteSubscriberDataAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestDeleteSubscriberDataAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewDeleteSubscriberDataAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &DeleteSubscriberDataAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestPurgeUERequest_Creation tests basic creation and initialization
func TestPurgeUERequest_Creation(t *testing.T) {
	msg := NewPurgeUERequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 321 {
		t.Errorf("Expected command code 321, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestPurgeUERequest_Validation tests field validation
func TestPurgeUERequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &PurgeUERequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewPurgeUERequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestPurgeUERequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestPurgeUERequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewPurgeUERequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &PurgeUERequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestPurgeUEAnswer_Creation tests basic creation and initialization
func TestPurgeUEAnswer_Creation(t *testing.T) {
	msg := NewPurgeUEAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 321 {
		t.Errorf("Expected command code 321, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestPurgeUEAnswer_Validation tests field validation
func TestPurgeUEAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &PurgeUEAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewPurgeUEAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestPurgeUEAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestPurgeUEAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewPurgeUEAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &PurgeUEAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestResetRequest_Creation tests basic creation and initialization
func TestResetRequest_Creation(t *testing.T) {
	msg := NewResetRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 322 {
		t.Errorf("Expected command code 322, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestResetRequest_Validation tests field validation
func TestResetRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &ResetRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewResetRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationHost = models_base.DiameterIdentity("server.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestResetRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestResetRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewResetRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationHost = models_base.DiameterIdentity("server.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &ResetRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationHost != original.DestinationHost {
		t.Errorf("DestinationHost mismatch: got %v, want %v", decoded.DestinationHost, original.DestinationHost)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestResetAnswer_Creation tests basic creation and initialization
func TestResetAnswer_Creation(t *testing.T) {
	msg := NewResetAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 322 {
		t.Errorf("Expected command code 322, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestResetAnswer_Validation tests field validation
func TestResetAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &ResetAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewResetAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestResetAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestResetAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewResetAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &ResetAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestNotifyRequest_Creation tests basic creation and initialization
func TestNotifyRequest_Creation(t *testing.T) {
	msg := NewNotifyRequest()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 323 {
		t.Errorf("Expected command code 323, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != true {
		t.Errorf("Expected Request flag true, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestNotifyRequest_Validation tests field validation
func TestNotifyRequest_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &NotifyRequest{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewNotifyRequest()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("client.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("client.example.com")
		msg.DestinationRealm = models_base.DiameterIdentity("server.example.com")
		msg.UserName = models_base.UTF8String("452040000000010")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestNotifyRequest_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestNotifyRequest_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewNotifyRequest()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("client.example.com")
	original.OriginRealm = models_base.DiameterIdentity("client.example.com")
	original.DestinationRealm = models_base.DiameterIdentity("server.example.com")
	original.UserName = models_base.UTF8String("452040000000010")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &NotifyRequest{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}
	if decoded.DestinationRealm != original.DestinationRealm {
		t.Errorf("DestinationRealm mismatch: got %v, want %v", decoded.DestinationRealm, original.DestinationRealm)
	}
	if decoded.UserName != original.UserName {
		t.Errorf("UserName mismatch: got %v, want %v", decoded.UserName, original.UserName)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}

// TestNotifyAnswer_Creation tests basic creation and initialization
func TestNotifyAnswer_Creation(t *testing.T) {
	msg := NewNotifyAnswer()

	// Verify header initialization
	if msg.Header.Version != 1 {
		t.Errorf("Expected version 1, got %d", msg.Header.Version)
	}

	if msg.Header.CommandCode != 323 {
		t.Errorf("Expected command code 323, got %d", msg.Header.CommandCode)
	}

	if msg.Header.ApplicationID != 16777251 {
		t.Errorf("Expected application ID 16777251, got %d", msg.Header.ApplicationID)
	}

	if msg.Header.Flags.Request != false {
		t.Errorf("Expected Request flag false, got %v", msg.Header.Flags.Request)
	}

	if msg.Header.Flags.Proxiable != true {
		t.Errorf("Expected Proxiable flag true, got %v", msg.Header.Flags.Proxiable)
	}
}

// TestNotifyAnswer_Validation tests field validation
func TestNotifyAnswer_Validation(t *testing.T) {
	t.Run("EmptyMessage", func(t *testing.T) {
		msg := &NotifyAnswer{}
		err := msg.Validate()
		if err == nil {
			t.Error("Expected validation error for empty message, got nil")
		}
	})

	t.Run("ValidMessage", func(t *testing.T) {
		msg := NewNotifyAnswer()
		msg.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
		msg.AuthSessionState = models_base.Enumerated(1)
		msg.OriginHost = models_base.DiameterIdentity("server.example.com")
		msg.OriginRealm = models_base.DiameterIdentity("server.example.com")

		err := msg.Validate()
		if err != nil {
			t.Errorf("Expected no validation error, got: %v", err)
		}
	})
}

// TestNotifyAnswer_MarshalUnmarshal tests Marshal and Unmarshal roundtrip
func TestNotifyAnswer_MarshalUnmarshal(t *testing.T) {
	// Create original message
	original := NewNotifyAnswer()
	original.SessionId = models_base.UTF8String("client.example.com;1234567890;1")
	original.AuthSessionState = models_base.Enumerated(1)
	original.OriginHost = models_base.DiameterIdentity("server.example.com")
	original.OriginRealm = models_base.DiameterIdentity("server.example.com")

	// Set header identifiers for comparison
	original.Header.HopByHopID = 0xAABBCCDD
	original.Header.EndToEndID = 0x11223344

	// Marshal original
	data, err := original.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal: %v", err)
	}

	// Unmarshal into new message
	decoded := &NotifyAnswer{}
	err = decoded.Unmarshal(data)
	if err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}

	// Verify header fields
	if decoded.Header.Version != original.Header.Version {
		t.Errorf("Version mismatch: got %d, want %d", decoded.Header.Version, original.Header.Version)
	}
	if decoded.Header.CommandCode != original.Header.CommandCode {
		t.Errorf("CommandCode mismatch: got %d, want %d", decoded.Header.CommandCode, original.Header.CommandCode)
	}
	if decoded.Header.ApplicationID != original.Header.ApplicationID {
		t.Errorf("ApplicationID mismatch: got %d, want %d", decoded.Header.ApplicationID, original.Header.ApplicationID)
	}
	if decoded.Header.HopByHopID != original.Header.HopByHopID {
		t.Errorf("HopByHopID mismatch: got 0x%X, want 0x%X", decoded.Header.HopByHopID, original.Header.HopByHopID)
	}
	if decoded.Header.EndToEndID != original.Header.EndToEndID {
		t.Errorf("EndToEndID mismatch: got 0x%X, want 0x%X", decoded.Header.EndToEndID, original.Header.EndToEndID)
	}

	if decoded.SessionId != original.SessionId {
		t.Errorf("SessionId mismatch: got %v, want %v", decoded.SessionId, original.SessionId)
	}
	if decoded.AuthSessionState != original.AuthSessionState {
		t.Errorf("AuthSessionState mismatch: got %d, want %d", decoded.AuthSessionState, original.AuthSessionState)
	}
	if decoded.OriginHost != original.OriginHost {
		t.Errorf("OriginHost mismatch: got %v, want %v", decoded.OriginHost, original.OriginHost)
	}
	if decoded.OriginRealm != original.OriginRealm {
		t.Errorf("OriginRealm mismatch: got %v, want %v", decoded.OriginRealm, original.OriginRealm)
	}

	// Marshal again and compare bytes
	data2, err := decoded.Marshal()
	if err != nil {
		t.Fatalf("Failed to marshal decoded message: %v", err)
	}

	if !bytes.Equal(data, data2) {
		t.Errorf("Marshaled data differs after roundtrip (len: %d vs %d)", len(data), len(data2))
	}
}
