// Code generated by diameter-codegen. DO NOT EDIT.

package s13

// Protocol Constants
const (
	S13_APPLICATION_ID               = 16777252
	VENDOR_ID_3GPP                   = 10415
	ECR_COMMAND_CODE                 = 324
	DIAMETER_ERROR_USER_UNKNOWN      = 5001
	DIAMETER_ERROR_EQUIPMENT_UNKNOWN = 5422
)

// AVP Codes
const (
	AVPCodeMIPHOMEAGENTHOST                      uint32 = 348
	AVPCodeORIGINHOST                            uint32 = 264
	AVPCodeORIGINREALM                           uint32 = 296
	AVPCodeITEMNUMBER                            uint32 = 1419
	AVPCodeREQUESTEDEUTRANAUTHENTICATIONINFO     uint32 = 1408
	AVPCodeCONFIDENTIALITYKEY                    uint32 = 1451
	AVPCodeSGSNNUMBER                            uint32 = 1489
	AVPCodeAMBR                                  uint32 = 1435
	AVPCodeTERMINATIONCAUSE                      uint32 = 295
	AVPCodeEXPERIMENTALRESULT                    uint32 = 297
	AVPCodeREAUTHREQUESTTYPE                     uint32 = 285
	AVPCodeIMMEDIATERESPONSEPREFERRED            uint32 = 1412
	AVPCodeMSISDN                                uint32 = 701
	AVPCodeERRORDIAGNOSTIC                       uint32 = 1614
	AVPCodeTERMINALINFORMATION                   uint32 = 1401
	AVPCodeSESSIONTIMEOUT                        uint32 = 27
	AVPCodeAUTHGRACEPERIOD                       uint32 = 276
	AVPCodeRESULTCODE                            uint32 = 268
	AVPCodePROXYSTATE                            uint32 = 33
	AVPCodeINBANDSECURITYID                      uint32 = 299
	AVPCodeACCESSRESTRICTIONDATA                 uint32 = 1426
	AVPCodeALLAPNCONFIGURATIONSINCLUDEDINDICATOR uint32 = 1428
	AVPCodeREDIRECTMAXCACHETIME                  uint32 = 262
	AVPCodeORIGINSTATEID                         uint32 = 278
	AVPCodeRATTYPE                               uint32 = 1032
	AVPCodeAPNCONFIGURATION                      uint32 = 1430
	AVPCodeCONTEXTIDENTIFIER                     uint32 = 1423
	AVPCodeINTEGRITYKEY                          uint32 = 1452
	AVPCodeMULTIROUNDTIMEOUT                     uint32 = 272
	AVPCodePRODUCTNAME                           uint32 = 269
	AVPCodeACCOUNTINGSUBSESSIONID                uint32 = 287
	AVPCodeGERANVECTOR                           uint32 = 1416
	AVPCodeSUBSCRIBERSTATUS                      uint32 = 1424
	AVPCodeEPSSUBSCRIBEDQOSPROFILE               uint32 = 1431
	AVPCodeNORFLAGS                              uint32 = 1443
	AVPCodeDESTINATIONHOST                       uint32 = 293
	AVPCodeERRORMESSAGE                          uint32 = 281
	AVPCodeUESRVCCCAPABILITY                     uint32 = 1615
	AVPCodeOPERATORDETERMINEDBARRING             uint32 = 1425
	AVPCodeUTRANVECTOR                           uint32 = 1415
	AVPCodeAPNOIREPLACEMENT                      uint32 = 1427
	AVPCodePROXYHOST                             uint32 = 280
	AVPCodeMIP6AGENTINFO                         uint32 = 486
	AVPCodeAUTHAPPLICATIONID                     uint32 = 258
	AVPCodeSOFTWAREVERSION                       uint32 = 1403
	AVPCodeAUTN                                  uint32 = 1449
	AVPCodeAUTHENTICATIONINFO                    uint32 = 1413
	AVPCodeKC                                    uint32 = 1453
	AVPCodeIDAFLAGS                              uint32 = 1441
	AVPCodeREDIRECTHOST                          uint32 = 292
	AVPCodeSUPPORTEDVENDORID                     uint32 = 265
	AVPCodeERRORREPORTINGHOST                    uint32 = 294
	AVPCodeACCTAPPLICATIONID                     uint32 = 259
	AVPCodeEQUIPMENTSTATUS                       uint32 = 1445
	AVPCodeIDRFLAGS                              uint32 = 1490
	AVPCodeREQUESTEDUTRANGERANAUTHENTICATIONINFO uint32 = 1409
	AVPCodeRAND                                  uint32 = 1447
	AVPCodeACCTMULTISESSIONID                    uint32 = 50
	AVPCodePROXYINFO                             uint32 = 284
	AVPCodeSESSIONBINDING                        uint32 = 270
	AVPCodeKASME                                 uint32 = 1450
	AVPCodeACCTSESSIONID                         uint32 = 44
	AVPCodeVENDORID                              uint32 = 266
	AVPCodeUSERNAME                              uint32 = 1
	AVPCodeMIPHOMEAGENTADDRESS                   uint32 = 334
	AVPCodeAUTHORIZATIONLIFETIME                 uint32 = 291
	AVPCodeDISCONNECTCAUSE                       uint32 = 273
	AVPCodeULAFLAGS                              uint32 = 1406
	AVPCodeRESYNCHRONIZATIONINFO                 uint32 = 1411
	AVPCodeSESSIONSERVERFAILOVER                 uint32 = 271
	AVPCodeCLASS                                 uint32 = 25
	AVPCodeSESSIONID                             uint32 = 263
	AVPCodeACCOUNTINGRECORDNUMBER                uint32 = 485
	AVPCodeDRMP                                  uint32 = 301
	AVPCodeCLRFLAGS                              uint32 = 1638
	AVPCodePURFLAGS                              uint32 = 1635
	AVPCodeAPNCONFIGURATIONPROFILE               uint32 = 1429
	AVPCodeAUTHREQUESTTYPE                       uint32 = 274
	AVPCodeACCOUNTINGRECORDTYPE                  uint32 = 480
	AVPCodeMIP6HOMELINKPREFIX                    uint32 = 125
	AVPCodeHOSTIPADDRESS                         uint32 = 257
	AVPCodeVENDORSPECIFICAPPLICATIONID           uint32 = 260
	AVPCodeDESTINATIONREALM                      uint32 = 283
	AVPCodeIMEI                                  uint32 = 1402
	AVPCodeEUTRANVECTOR                          uint32 = 1414
	AVPCodeEVENTTIMESTAMP                        uint32 = 55
	AVPCodeFIRMWAREREVISION                      uint32 = 267
	AVPCode3GPP2MEID                             uint32 = 1471
	AVPCodeDSAFLAGS                              uint32 = 1422
	AVPCodeVISITEDPLMNID                         uint32 = 1407
	AVPCodeXRES                                  uint32 = 1448
	AVPCodeCANCELLATIONTYPE                      uint32 = 1420
	AVPCodeSUBSCRIPTIONDATA                      uint32 = 1400
	AVPCodeFAILEDAVP                             uint32 = 279
	AVPCodeE2ESEQUENCE                           uint32 = 300
	AVPCodeROUTERECORD                           uint32 = 282
	AVPCodeALERTREASON                           uint32 = 1434
	AVPCodeDSRFLAGS                              uint32 = 1421
	AVPCodeULRFLAGS                              uint32 = 1405
	AVPCodeSRES                                  uint32 = 1454
	AVPCodeACCTINTERIMINTERVAL                   uint32 = 85
	AVPCodeAUTHSESSIONSTATE                      uint32 = 277
	AVPCodeACCOUNTINGREALTIMEREQUIRED            uint32 = 483
	AVPCodeEXPERIMENTALRESULTCODE                uint32 = 298
	AVPCodeAIRFLAGS                              uint32 = 1679
	AVPCodeAMSISDN                               uint32 = 1643
	AVPCodeSERVICESELECTION                      uint32 = 493
	AVPCodeREDIRECTHOSTUSAGE                     uint32 = 261
	AVPCodePUAFLAGS                              uint32 = 1442
	AVPCodeCSGSUBSCRIPTIONDATA                   uint32 = 1436
	AVPCodeNUMBEROFREQUESTEDVECTORS              uint32 = 1410
)

// Vendor IDs
const (
	VendorID10415 uint32 = 10415
)

// Command Codes
const (
	CommandCodeMEIDENTITYCHECKREQUEST uint32 = 324
	CommandCodeMEIDENTITYCHECKANSWER  uint32 = 324
)

// EquipmentStatus represents the EquipmentStatus enumerated type
type EquipmentStatus uint32

// EquipmentStatus values
const (
	EquipmentStatus_GREYLISTED  EquipmentStatus = 2
	EquipmentStatus_WHITELISTED EquipmentStatus = 0
	EquipmentStatus_BLACKLISTED EquipmentStatus = 1
)
